import type { Metadata } from "next";

import { Geist, Geist_Mono } from "next/font/google";

import { Jost } from "next/font/google";

import "./globals.scss";
import Header from "@/shared/ui/Layout/Header";
import Footer from "@/shared/ui/Layout/Footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { ReduxProvider } from "@/shared/lib/redux/provider";
import { AuthProvider } from "@/shared/hook/AuthContext/ui/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const jost = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${jost.variable} bona antialiased`}>
        <AuthProvider>
          <ReduxProvider>
            <div className="flex flex-col min-h-screen">
              <ToastContainer />
              <Header />
              {children}
              <Footer />
            </div>
          </ReduxProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
